#+STARTUP: overview
Hi, welcome to the Matrix Knowledge Base.

Don't be put off by Github's horrible attempt at rendering this. It's much better with a proper tool. (See the FAQ FAQ)

* FAQ
** FAQ FAQ

Questions about this FAQ and directory itself.

*** What is this?

This is at the moment both a FAQ and a directory for the Matrix ecosystem in the widest sense possible.

*** What is it written in?

This document is written in Org mode format. See http://orgmode.org for more information.

*** What tools are used to author and render this?
**** Authoring

An android app called Orgzly, which is available from F-Droid. Homepage at http://www.orgzly.com

**** Synchronizing

MGit: https://github.com/maks/MGit

**** Rendering :fixme:

(none, so far)

*** Isn't there _already_ a Matrix FAQ?

Yes. This document even links to it at the top of the Matrix section.

*** So why another FAQ?
**** Knowledge about Matrix is highly scattered across many deep-linked documents. This KB brings them together in a comprehensive overview, and links to them.
**** This Knowledge Base is not merely a Matrix FAQ: it also has FAQs for some of its popular clients and tools, such as Riot. Moreover, it is also a directory, curating a wide spectrum of software which works with Matrix in one way or another.
**** Using the Org mode format with the Orgzly app lets me more easily curate the questions and answers on my mobile phone.
**** It is intended to eventually allow bidirectional conversion of (sections of) this KB, allowing one to wholly import external FAQs, work on them, and then contribute back, keeping everything in sync.
**** There are plans for a FAQbot. The Org mode format is very suitable for automatic processing, and one day a bot could be answering questions in Matrix rooms, drawing on this KB for its knowledge.
*** I have questions or suggestions for this FAQ itself. Where can I go to talk to a human?

The Matrix Knowledge Base has a dedicated room at [[https://matrix.to/#/#mkb:matrix.org][#matrix-knowledge-base:matrix.org]]. This room is not for general Matrix questions. For those, see the rest of this FAQ.

** Riot
*** Web and Desktop
**** I'm getting CORS errors. What's wrong? :CORS:
:PROPERTIES:
:source:   https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/%2414899602502111244BtYeL:matrix.org
:END:

CORS errors are generally not actually anything to do with CORS, but hide a plain http error, e.g. a 500, which is the real reason why the thing is failing.

However, as plain errors don't have CORS headers, it gives this confusing warning.

**** How can I change the language?

This is not yet possible.

**** What is the best way to contribute a translation?

Riot-Web currently lacks the infrastructure to support i18n, and as such, does not accept translations at this point in time.

https://matrix.to/#/#riot:matrix.org/%241487935362359914vmevo:matrix.org has the latest word on it.

***** [[https://matrix.to/#/@MTRNord:matrix.eclabs.de][MTRNord]] is currently working on adding the necessary i18n infrastructure:
:PROPERTIES:
:source:   https://matrix.to/#/#riot:matrix.org/%2414900026486026TwjNl:matrix.eclabs.de
:END:

If anyone is interested: I work currently on making Translations in RiotWeb possible. My work is based on the master currently. If anyone wants to add transations take a look at the files in ./src/i18n in these 2 repos: https://github.com/MTRNord/matrix-react-sdk/tree/translations  and   https://github.com/MTRNord/riot-web/tree/translation

PS: I am still working on that so There isn't yet every string translated and also there are maybe some bugs

**** My question isn't answered here. Where can I ask for help?

The Web and Desktop versions of Riot have a dedicated room at [[https://matrix.to/#/#riot:matrix.org][#riot:matrix.org]] for user questions. Please note that this is also the place for general issues which encompass _all_ Riot platforms. (Web, Desktop, Android, iOS.)

Developers coordinate their efforts in [[https://matrix.to/#/#riot-dev:matrix.org][#riot-dev:matrix.org]].

*** Android
**** How can I input (unicode) emoji? :emoji:

See http://www.wikihow.com/Get-Emoji-on-Android

**** How do I join an existing room? (For example, #riot-android:matrix.org) :join_room:

From the main ("Messages") screen, Press the magnifying glass and type the room alias into the search field.

**** How can I change the language?

This is not yet possible.

**** What is the best way to contribute a translation?

The Riot-Android maintainers don't seem to be taking translations at the moment. In this author's opinion, your time is better spent elsewhere, until Riot actively invites i18n contributions.

https://matrix.to/#/#riot-android:matrix.org/%241487938480379751GMruq:matrix.org has the last word on it.

Related issues:
- [[https://github.com/vector-im/riot-android/issues/811][#811 How can I translate the app?]]
- [[https://github.com/vector-im/riot-android/pull/1046][#1046 Offering translation into Russian]]
- [[https://github.com/vector-im/riot-android/issues/759][#759 translate inteface to pl]]
- [[https://github.com/vector-im/riot-android/pull/660][#660 add portugese language]

**** My question isn't answered here. Where can I ask for help?

Riot-Android version has a dedicated room at [[https://matrix.to/#/#riot-android:matrix.org][#riot-android:matrix.org]] for both user questions and developer talk.

*** iOS
**** My question isn't answered here. Where can I ask for help?

Riot-iOS version has a dedicated room at [[https://matrix.to/#/#riot-ios:matrix.org][#riot-ios:matrix.org]] for both user questions and developer talk.

** Synapse
*** How do I enable the built-in web client? :fixme:

Don't. It's deprecated. Either use Riot at https://riot.im/app with a (your) custom server, or download a Riot tarball from *X* and host it yourself.

*** My question isn't answered here. Where can I ask for help?

There doesn't seem to be a dedicated official room for Synapse. You can try your questions in [[https://matrix.to/#/#matrix:matrix.org][#matrix:matrix.org]], or if they're highly technical, in [[https://matrix.to/#/#matrix-dev:matrix.org][#matrix-dev:matrix.org]].

A community-run room also exists at [[https://matrix.to/#/#synapse-community:matrix.org][#synapse-community:matrix.org]]. Although this doesn't have official backing from the Synapse developers, it might offer a more relaxed space for the beginning Synapse user, as opposed to the official rooms where your question might quickly scroll out of view, going unanswered.

** Dendrite
*** So what's the latest word on Dendrite?
:PROPERTIES:
:Source:   https://twitter.com/matrixdotorg/status/841814171666808833
:END:

Exciting times - Dendrite (the next generation Golang matrix server) just received its first messages!! https://matrix.org/blog/2017/03/15/dendrite-receives-its-first-messages/ #golang

*** My question isn't answered here. Where can I ask for help?

Rooms will be listed here when Dendrite is usable.

** Matrix
*** The official Matrix FAQ

- https://matrix.org/docs/guides/faq.html

*** What is the Matrix?

Unfortunately, no one can be told what the Matrix is. You have to see it for yourself.

*** I can see everyone's devices! Isn't that a privacy issue?
:PROPERTIES:
:source:   https://matrix.to/#/#matrix:matrix.org/%241489661409560128pTiCo:matrix.org
:END:

Yes, this is a known metadata leak. Other than renaming your devices, there isn't much that can be done about it.

Ironically, e2e encryption reduces privacy in some ways. Since Matrix e2e encrypts to each device separately, it needs to know which devices those are. This is a privacy vs. features tradeoff. Most competing encrypted messengers don't allow multiple devices.

*** My question isn't answered here. Where can I ask for help?

General Matrix questions can be asked in [[https://matrix.to/#/#matrix:matrix.org][#matrix:matrix.org]]. If you're building on top of Matrix, please join [[https://matrix.to/#/#matrix-dev:matrix.org][#matrix-dev:matrix.org]].

* Bridges
** Discord
*** Half-Shot :fixme:

- #discord:half-shot.uk

** My question isn't answered here. Where can I ask for help?

Irc bridges have a dedicated room at [[https://matrix.to/#/#irc:matrix.org][#irc:matrix.org]] for both user questions and developer talk.

All other bridges can be discussed at [[https://matrix.to/#/#bridges:matrix.org][#bridges:matrix.org]].

* Frameworks
** Python
*** python-matrix-bot-api (shawnanastasio)
:PROPERTIES:
:source:   https://github.com/shawnanastasio/python-matrix-bot-api
:END:

@shawnanastasio:matrix.anastas.io said:

Hi all, sorry for the shameless self promotion, but I made a python client to easily create Matrix bots with:

- https://github.com/shawnanastasio/python-matrix-bot-api

Any feedback would be greatly appreciated!

* Applications
** Blogging
*** J (Luke Barnard)

There is "j", which is a full-featured blogging system including comments.
- https://github.com/lukebarnard1/j

* Keywords (old, to be reworked)

This contains the keywords that were taught to *mubot* at some point. An update to mubot means this information is now "lost". It is being reconstructed here, for the purpose of eventually integrating it into the FAQ/Directory properly.

** 3pid

In the context of Matrix, any identifier which is not a Matrix ID. This includes e-mail addresses, phone numbers, Facebook accounts, etc.

** alias :missing:
** balancing interop and privacy

[Slides] Matthew talks about the challenge of balancing interoperability and privacy: https://matrix.org/~matthew/2016-12-22%20Matrix%20Balancing%20Interop%20and%20Privacy.pdf

** Code of Conduct
*** Riot

???

*** Matrix

This code of conduct outlines our expectations for participants within the Matrix community, as well as steps for reporting unacceptable behaviour. We are committed to providing a welcoming and inspiring community for all, and expect our code of conduct to be honoured. Anyone who violates this code of conduct may be banned from the community.

- https://matrix.org/docs/guides/code_of_conduct.html

** crypto export

The export of cryptographic technology and devices from the United States was severely restricted by U.S. law until 1992, but was gradually eased until 2000. Some restrictions still remain. https://en.wikipedia.org/wiki/Export_of_cryptography_from_the_United_States

** desktop app :missing:
** e2e implementation guide :missing:
** emacs client

See https://fort.kickass.systems/git/rrix/matrix-client.git

** exul slides :missing:
** federation tester :missing:
** gc :missing:
** go-neb

Multi-purpose Matrix bot. https://github.com/matrix-org/go-neb

** id :missing:
** identity server :missing:
** irc network list :missing:
** ivar

https://github.com/torhve/ivar2

** matrigram

If anyone is interested in using a telegram bridge, we'd love to hear some feedback https://github.com/GalPressman/matrigram

** matrix on freenode :missing:
** matrix-recorder

Okay, I think a first version is finally done: https://gitlab.com/argit/matrix-recorder - the idea is that the tool would allow you to keep a record of your conversations, as Riot does not yet allow you to export your message history in a format suitable for safekeeping.

** migrating to postgres :missing:
** mubot

https://github.com/davidar/hubot-matrix

** mxid :missing:
** network list :missing:
** olm :missing:
** receipt :missing:
** reindex

TIL that PostgreSQL may have internal fragmentation in the btrees used for indexes, and that can cause VACUUM FULL to make the database bigger... which can be solved by issuing a REINDEX DATABASE - https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/%2414835668811638615xXMYC:matrix.org

** screen sharing :missing:
** setting up federation

https://github.com/matrix-org/synapse#setting-up-federation has words on it.

** slack bridge
*** Matrix-org

https://github.com/matrix-org/matrix-appservice-slack

*** kfatehi

https://github.com/kfatehi/matrix-appservice-slack

** slack hook

See https://matrix.to/#/!svJUttHBtRMdXmEhEy:matrix.org/$14836112541869035fxcVU:matrix.org

** synpurge :fixme:

Utility script to Matrix room history purge room in Synapse https://github.com/aperezdc/synpurge. Synpurge has reached v4! https://pypi.python.org/pypi/synpurge/4

** telegram bridge
*** telematrix (Sijmen Schoon)

https://github.com/SijmenSchoon/telematrix

** those little circles :missing:
** upgrade script :missing:
** webrtc tutorial
*** Basics

https://www.html5rocks.com/en/tutorials/webrtc/basics/

*** Infrastructure

https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

** xmpp bridge
*** matrix-xmpp-bridge

https://github.com/pztrn/matrix-xmpp-bridge

*** xmpptrix

https://github.com/SkaveRat/xmpptrix

** yzord :missing:
* Processing Queue

Things which probably need to be added, but need a closer look.

** https://github.com/turt2live/matrix-appservice-instagram
** The IRC wish list is at https://github.com/matrix-org/matrix-appservice-irc/issues/208, and geekshed is already on the list.
** What happens if I mark a room as "direct chat"? Does it effect anything? :needsanswer:
** A shell script for tagging rooms

https://gist.github.com/turt2live/697d5b3781fb7ab7e11d704ea90e3dbe

** There are a couple of community-written users guides linked to in this issue as well: https://github.com/vector-im/riot-web/issues/3308
