#+STARTUP: overview
Hi, welcome to the Matrix Knowledge Base.

Don't be put off by Github's horrible attempt at rendering this. It's much better with a proper tool. (See the FAQ FAQ.)

* FAQ :faq:
** FAQ FAQ

Questions about this FAQ and directory itself.

*** What is this?

This is at the moment both a FAQ and a directory for the Matrix ecosystem in the widest sense possible.

*** What is it written in?

This document is written in Org mode format. See http://orgmode.org for more information.

*** What tools are used to author and render this?
**** Authoring

[[http://www.orgzly.com][Orgzly for Android]], which is also available from [[https://f-droid.org/app/com.orgzly][F-Droid]].

**** Synchronizing

MGit: https://github.com/maks/MGit

**** Rendering :fixme:

(none, so far)

*** Isn't there _already_ a Matrix FAQ?

Yes. This document even links to it at the top of the Matrix section.

*** So why another FAQ?

- Knowledge about Matrix is scattered across many deep-linked documents. This KB brings them together in a comprehensive overview, and links to them.
- This Knowledge Base is not merely a Matrix FAQ: it also has FAQs for some of its popular clients and tools, such as Riot. Moreover, it is also a directory, curating a wide spectrum of software which works with Matrix in one way or another.
- Using the Org mode format with the Orgzly app lets me more easily curate the questions and answers on my mobile phone.
- It is intended to eventually allow bidirectional conversion of (sections of) this KB, allowing one to wholly import external FAQs, work on them, and then contribute back, keeping everything in sync.
- There are plans for a FAQbot. The Org mode format is very suitable for automatic processing, and one day a bot could be answering questions in Matrix rooms, drawing on this KB for its knowledge.

*** I have questions or suggestions for this FAQ itself. Where can I go to talk to a human?

The Matrix Knowledge Base has a dedicated room at [[https://matrix.to/#/#mkb:matrix.org][#matrix-knowledge-base:matrix.org]]. This room is not for general Matrix questions. For those, see the rest of this FAQ.

** Riot :riot:
*** Web and Desktop :web:desktop:
**** I'm getting CORS errors. What's wrong? :CORS:
:PROPERTIES:
:source:   https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/%2414899602502111244BtYeL:matrix.org
:END:

CORS errors are generally not actually anything to do with CORS, but hide a plain http error, e.g. a 500, which is the real reason why the thing is failing.

However, as plain errors don't have CORS headers, it gives this confusing warning.

**** How can I change the language?

This is not yet possible.

**** What is the best way to contribute a translation? :i18n:

Riot-Web currently lacks the infrastructure to support i18n, and as such, does not accept translations at this point in time.

https://matrix.to/#/#riot:matrix.org/%241487935362359914vmevo:matrix.org has the latest word on it.

***** [[https://matrix.to/#/@MTRNord:matrix.eclabs.de][MTRNord]] is currently working on adding the necessary i18n infrastructure:
:PROPERTIES:
:source:   https://matrix.to/#/#riot:matrix.org/%2414900026486026TwjNl:matrix.eclabs.de
:END:

#+BEGIN_QUOTE
If anyone is interested: I work currently on making Translations in RiotWeb possible. My work is based on the master currently. If anyone wants to add transations take a look at the files in ./src/i18n in these 2 repos: https://github.com/MTRNord/matrix-react-sdk/tree/translations  and   https://github.com/MTRNord/riot-web/tree/translation

PS: I am still working on that so There isn't yet every string translated and also there are maybe some bugs
#+END_QUOTE

**** My question isn't answered here. Where can I ask for help?

The Web and Desktop versions of Riot have a dedicated room at [[https://matrix.to/#/#riot:matrix.org][#riot:matrix.org]] for user questions. Please note that this is also the place for general issues which encompass _all_ Riot platforms. (Web, Desktop, Android, iOS.)

Developers coordinate their efforts in [[https://matrix.to/#/#riot-dev:matrix.org][#riot-dev:matrix.org]].

*** Android :android:
**** How can I input (unicode) emoji? :emoji:

See http://www.wikihow.com/Get-Emoji-on-Android

**** How do I join an existing room? (For example, #riot-android:matrix.org) :join_room:

From the main ("Messages") screen, Press the magnifying glass and type the room alias into the search field.

**** How can I change the language? :needsverification:

This is not yet possible. However, it should automatically switch to your phone's system language, if a translation is available.

**** What is the best way to contribute a translation? @@html:<a name="translate-android">@@ :i18n:

*Important*: Before contributing anything, please read [[https://github.com/vector-im/riot-android/blob/master/CONTRIBUTING.rst][Contributing code to Matrix]] carefully and make sure you understand and agree with everything written therein.

After having read [[https://github.com/vector-im/riot-android/blob/master/CONTRIBUTING.rst][Contributing code to Matrix]], the best way to contribute your translation is to send a pull request against the ~develop~ branches of [[https://github.com/vector-im/riot-android][riot-android]] and [[https://github.com/matrix-org/matrix-android-sdk][matrix-android-sdk]].

Translatable strings are in ~res/values/strings.xml~ and ~res/values/array.xml~, and should go to ~res/values-xx/strings.xml~ and ~res/values-xx/array.xml~, respectively, where ~xx~ is the lower-case two-letter language code.

To see an example of what a pull request should look like, take a look at [[https://github.com/vector-im/riot-android/pull/1046][pull #1046: Offering translation into Russian]].

(This pull request is not necessarily an example that stands above all others, and was chosen at random, after some minimal verification.)

*Important*: Translations must be made against the ~develop~ branch, /not/ +master+.

[[https://github.com/matrix-org/matrix-android-sdk][matrix-android-sdk]] needs to be translated as well.

Tip: Android Studio has a
[[https://developer.android.com/studio/write/translations-editor.html][Translations Editor]].

***** Related issues

- [[https://github.com/vector-im/riot-android/issues/811][#811 How can I translate the app?]]
- [[https://github.com/vector-im/riot-android/pull/1046][#1046 Offering translation into Russian]]
- [[https://github.com/vector-im/riot-android/issues/759][#759 translate inteface to pl]]
- [[https://github.com/vector-im/riot-android/pull/660][#660 add portugese language]]
- [[https://github.com/vector-im/riot-android/issues/357][#357 Internationalise vector]]

**** My question isn't answered here. Where can I ask for help?

Riot-Android version has a dedicated room at [[https://matrix.to/#/#riot-android:matrix.org][#riot-android:matrix.org]] for both user questions and developer talk.

*** iOS :ios:
**** My question isn't answered here. Where can I ask for help?

Riot-iOS has a dedicated room at [[https://matrix.to/#/#riot-ios:matrix.org][#riot-ios:matrix.org]] for both user questions and developer talk.

** Synapse
*** How do I enable the built-in web client? :fixme:

Don't. It's deprecated. Either use Riot at https://riot.im/app with a (your) custom server, or download a Riot tarball from *X* and host it yourself.

*** My question isn't answered here. Where can I ask for help?

The designated place to ask questions about Synapse is [[https://matrix.to/#/#matrix:matrix.org][#matrix:matrix.org]], or if the questions are more technical, in [[https://matrix.to/#/#matrix-dev:matrix.org][#matrix-dev:matrix.org]].

A community-run room also exists at [[https://matrix.to/#/#synapse-community:matrix.org][#synapse-community:matrix.org]]. Although the room doesn't have official backing from the Synapse developers, it is exclusively dedicated to Synapse, and as such, can offer more focus.

** Dendrite
*** So what's the latest word on Dendrite?
:PROPERTIES:
:Source:   https://twitter.com/matrixdotorg/status/841814171666808833
:END:

Exciting times - Dendrite (the next generation Golang matrix server) just received its first messages!! https://matrix.org/blog/2017/03/15/dendrite-receives-its-first-messages/ #golang

*** My question isn't answered here. Where can I ask for help?

Rooms will be listed here when Dendrite is usable.

** Matrix
*** The official Matrix FAQ

- https://matrix.org/docs/guides/faq.html

*** What is the Matrix?

Unfortunately, no one can be told what the Matrix is. You have to see it for yourself.

*** I can see everyone's devices! Isn't that a privacy issue?
:PROPERTIES:
:source:   https://matrix.to/#/#matrix:matrix.org/%241489661409560128pTiCo:matrix.org
:END:

Yes, this is a known metadata leak. Other than renaming your devices, there isn't much that can be done about it.

Ironically, e2e encryption reduces privacy in some ways. Since Matrix e2e encrypts to each device separately, it needs to know which devices those are. This is a privacy vs. features tradeoff. Most competing encrypted messengers don't allow multiple devices.

*** My question isn't answered here. Where can I ask for help?

General Matrix questions can be asked in [[https://matrix.to/#/#matrix:matrix.org][#matrix:matrix.org]]. If you're building on top of Matrix, please join [[https://matrix.to/#/#matrix-dev:matrix.org][#matrix-dev:matrix.org]].

* Bridges
** Discord
*** Half-Shot :fixme:

- #discord:half-shot.uk

** Instagram

- Status: Pre-alpha (not working yet)
- Site: https://github.com/turt2live/matrix-appservice-instagram
- Availability: self-hosting required

** IRC
*** Bridged Networks

| Name     | Room format                      | User format                     | Comment                 |
|----------+----------------------------------+---------------------------------+-------------------------|
| Freenode | =#freenode_#channame:matrix.org= | =@freenode_nickname:matrix.org= | /No leading underscore/ |
| Moznet   | =#mozilla_#channame:matrix.org=  |                                 | /No leading underscore/ |
| OFTC     | =#_oftc_#channame:matrix.org=    |                                 |                         |
| Snoonet  | =#_snoonet_#channame:matrix.org= |                                 |                         |
| hackint  | =#channame:irc.hackint.org=      | =@irc_nickname:irc.hackint.org= | Hosted by hackint       |
| GIMPNet  | =#_gimpnet_#channame:matrix.org= |                                 |                         |

Another nice-looking list is [[https://github.com/matrix-org/matrix-appservice-irc/wiki/Bridged-IRC-networks][on the wiki]].

The /official/ IRC network (wish)list can be [[https://github.com/matrix-org/matrix-appservice-irc/issues/208][found here]].

*** Non-bridged networks (wishlist)

The official IRC network wishlist can be [[https://github.com/matrix-org/matrix-appservice-irc/issues/208][found here]].

*** matrix-appservice-irc

The software which runs the official [[https://matrix.org][matrix.org]]-hosted IRC bridges is at [[https://github.com/matrix-org/matrix-appservice-irc]].

It has a Matrix room at [[https://matrix.to/#/#irc:matrix.org][#irc:matrix.org]] for both user questions and developer talk.

** My question isn't answered here. Where can I ask for help?

Irc bridges have a dedicated room at [[https://matrix.to/#/#irc:matrix.org][#irc:matrix.org]] for both user questions and developer talk.

All other bridges can be discussed at [[https://matrix.to/#/#bridges:matrix.org][#bridges:matrix.org]].

* Frameworks
** Python
*** python-matrix-bot-api (shawnanastasio)
:PROPERTIES:
:source:   https://github.com/shawnanastasio/python-matrix-bot-api
:END:

@shawnanastasio:matrix.anastas.io said:

Hi all, sorry for the shameless self promotion, but I made a python client to easily create Matrix bots with:

- https://github.com/shawnanastasio/python-matrix-bot-api

Any feedback would be greatly appreciated!

* Applications
** Blogging
*** J (Luke Barnard)

There is "j", which is a full-featured blogging system including comments.
- https://github.com/lukebarnard1/j

* Keywords (old, to be reworked)

This contains the keywords that were taught to *mubot* at some point. An update to mubot means this information is now "lost". It is being reconstructed here, for the purpose of eventually integrating it into the FAQ/Directory properly.

** 3pid

In the context of Matrix, any identifier which is not a Matrix ID. This includes e-mail addresses, phone numbers, Facebook accounts, etc.

** alias :missing:
** balancing interop and privacy

[Slides] Matthew talks about the challenge of balancing interoperability and privacy: https://matrix.org/~matthew/2016-12-22%20Matrix%20Balancing%20Interop%20and%20Privacy.pdf

** Code of Conduct
*** Riot

???

*** Matrix

This code of conduct outlines our expectations for participants within the Matrix community, as well as steps for reporting unacceptable behaviour. We are committed to providing a welcoming and inspiring community for all, and expect our code of conduct to be honoured. Anyone who violates this code of conduct may be banned from the community.

- https://matrix.org/docs/guides/code_of_conduct.html

** crypto export

The export of cryptographic technology and devices from the United States was severely restricted by U.S. law until 1992, but was gradually eased until 2000. Some restrictions still remain. https://en.wikipedia.org/wiki/Export_of_cryptography_from_the_United_States

** desktop app :missing:
** e2e implementation guide :missing:
** emacs client

See https://fort.kickass.systems/git/rrix/matrix-client.git

** exul slides :missing:
** federation tester :missing:
** gc :missing:
** go-neb

Multi-purpose Matrix bot. https://github.com/matrix-org/go-neb

** id :missing:
** identity server :missing:
** irc network list :missing:
** ivar

https://github.com/torhve/ivar2

** matrigram

If anyone is interested in using a telegram bridge, we'd love to hear some feedback https://github.com/GalPressman/matrigram

** matrix on freenode :missing:
** matrix-recorder

Okay, I think a first version is finally done: https://gitlab.com/argit/matrix-recorder - the idea is that the tool would allow you to keep a record of your conversations, as Riot does not yet allow you to export your message history in a format suitable for safekeeping.

** migrating to postgres :missing:
** mubot

https://github.com/davidar/hubot-matrix

** mxid :missing:
** network list :missing:
** olm :missing:
** receipt :missing:
** reindex

TIL that PostgreSQL may have internal fragmentation in the btrees used for indexes, and that can cause VACUUM FULL to make the database bigger... which can be solved by issuing a REINDEX DATABASE - https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/%2414835668811638615xXMYC:matrix.org

** screen sharing :missing:
** setting up federation

https://github.com/matrix-org/synapse#setting-up-federation has words on it.

** slack bridge
*** Matrix-org

https://github.com/matrix-org/matrix-appservice-slack

*** kfatehi

https://github.com/kfatehi/matrix-appservice-slack

** slack hook

See https://matrix.to/#/!svJUttHBtRMdXmEhEy:matrix.org/$14836112541869035fxcVU:matrix.org

** synpurge :fixme:

Utility script to Matrix room history purge room in Synapse https://github.com/aperezdc/synpurge. Synpurge has reached v4! https://pypi.python.org/pypi/synpurge/4

** telegram bridge
*** telematrix (Sijmen Schoon)

https://github.com/SijmenSchoon/telematrix

** those little circles :missing:
** upgrade script :missing:
** webrtc tutorial
*** Basics

https://www.html5rocks.com/en/tutorials/webrtc/basics/

*** Infrastructure

https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

** xmpp bridge
*** matrix-xmpp-bridge

https://github.com/pztrn/matrix-xmpp-bridge

*** xmpptrix

https://github.com/SkaveRat/xmpptrix

** yzord :missing:
* Processing Queue

Things which should probably be added, but need to be reworked, or need a closer look.

(This section is mainly an artifact of me not being able to file or access issues offline.)

** What happens if I mark a room as "direct chat"? Does it effect anything? :needsanswer:
** A shell script for tagging rooms

https://gist.github.com/turt2live/697d5b3781fb7ab7e11d704ea90e3dbe

** There are a couple of community-written users guides linked to in this issue as well: https://github.com/vector-im/riot-web/issues/3308
** hmm, right, I don't think there's the concept of an admin user on matrix

there is, but it is very limited
you must enable it by editing your user row on the database
and there is only two api two delete old history and old medias

is that documented somewhere?

yep: https://github.com/matrix-org/synapse/tree/master/docs/admin_api

https://matrix.to/#/!svJUttHBtRMdXmEhEy:matrix.org/%24149022212811cUBkh:orbstheorem.ch
#bridges:matrix.org

** https://github.com/matrix-org/synapse/wiki#i-have-a-problem-with-my-server-can-i-just-delete-my-database-and-start-again
** i'm still wondering if our IPs are protected on Riot or not.. no one can obtain it right?

Only the server admin can see the IP (of course).
Nobody else can, the ip is not propagated in any way.
well, it is if you make a 1:1 call
Oh right, that's true.
Voice and video calls are peer-to-peer, so of necessity the IPs have to be exchanged.
Worse is that it sends all known interface addresses, including local (private) network addresses.
Which is actually awesome if you're actually placing a call to someone on the same private network.
But also cause for (privacy) concerns.
If it is of great concern, the solution is to neither place nor accept voice and video calls.

https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/%2414902634851380909LwydX:matrix.org
#matrix:matrix.org

** How to get my access token ?

https://matrix.to/#/#matrix:matrix.org/%2414902578321344171PDCNZ:matrix.org

** Add #hello-matrix:matrix.org and hello-matrix.net
** I found the icons missing after the nginx reverse proxy, any sample nginx config for riot-web?

FYI. It caused by X-Frame-Options set to deny. Now I use the SAMEORIGIN and problem solved.

https://matrix.to/#/!DgvjtOljKujDBrxyHk:matrix.org/%2414903176841958169Wkaps:matrix.org
#riot:matrix.org

** Add GCM replacements

Add here and to riot-android#1066

