#+STARTUP: overview
Hi, welcome to the Matrix Knowledge Base.

Don't be put off by Github's horrible attempt at rendering this. It's much better with a proper tool. (See the FAQ FAQ)

* FAQ
** FAQ FAQ

Questions about this FAQ and directory itself.

*** What is this?

This is at the moment both a FAQ and a directory for the Matrix ecosystem in the widest sense possible.

*** What is it written in?

This document is written in Org mode format. See http://orgmode.org for more information.

*** What tools are used to author and render this?
**** Authoring

An android app called Orgzly, which is available from F-Droid. Homepage at http://www.orgzly.com

**** Rendering :fixme:

(none, so far)

*** Isn't there /already/ a Matrix FAQ?

Yes. This document even links to it at the top of the Matrix section.

*** So why another FAQ?
**** Knowledge about Matrix is highly scattered across many deep-linked documents. This KB brings them together in a comprehensive overview, and links to them.
**** This Knowledge Base is not merely a Matrix FAQ: it also has FAQs for some of its popular clients and tools, such as Riot. Moreover, it is also a directory, curating a wide spectrum of software which works with Matrix in one way or another.
**** Using the Org mode format with the Orgzly app lets me more easily curate the questions and answers.
**** It is intended to eventually allow bidirectional conversion of (sections of) this KB, allowing one to wholly import external FAQs, work on them, and then contribute back, keeping everything in sync.
**** There are plans for a FAQbot. The Org mode format is very suitable for automatic processing, and one day a bot could be answering questions in Matrix rooms, drawing on this KB for its knowledge.
** Riot
*** Web
*** Android
*** iOS
** Synapse
** Dendrite
** Matrix
*** The Matrix FAQ

- https://matrix.org/docs/guides/faq.html

* Bridges
** Discord
*** Half-Shot :fixme:

- #discord:half-shot.uk

* Frameworks
** Python
*** python-matrix-bot-api (shawnanastasio)

@shawnanastasio:matrix.anastas.io said:

Hi all, sorry for the shameless self promotion, but I made a python client to easily create Matrix bots with:

- https://github.com/shawnanastasio/python-matrix-bot-api

Any feedback would be greatly appreciated!

https://matrix.to/#/#matrix:matrix.org/%24148730913815005AqGXp:matrix.anastas.io

* Applications
** Blogging
*** J (Luke Barnard)

There is "j", which is a full-featured blogging system including comments.
- https://github.com/lukebarnard1/j

* Keywords (old, to be reworked)

This contains the keywords that were taught to *mubot* at some point. An update to mubot means this information is now "lost". It is being reconstructed here, for the purpose of eventually integrating it into the FAQ/Directory properly.

** 3pid

In the context of Matrix, any identifier which is not a Matrix ID. This includes e-mail addresses, phone numbers, Facebook accounts, etc.

** alias :missing:
** balancing interop and privacy

[Slides] Matthew talks about the challenge of balancing interoperability and privacy: https://matrix.org/~matthew/2016-12-22%20Matrix%20Balancing%20Interop%20and%20Privacy.pdf

** Code of Conduct
*** Riot

???

*** Matrix

This code of conduct outlines our expectations for participants within the Matrix community, as well as steps for reporting unacceptable behaviour. We are committed to providing a welcoming and inspiring community for all, and expect our code of conduct to be honoured. Anyone who violates this code of conduct may be banned from the community.

- https://matrix.org/docs/guides/code_of_conduct.html

** crypto export

The export of cryptographic technology and devices from the United States was severely restricted by U.S. law until 1992, but was gradually eased until 2000. Some restrictions still remain. https://en.wikipedia.org/wiki/Export_of_cryptography_from_the_United_States

** desktop app :missing:
** e2e implementation guide :missing:
** emacs client

See https://fort.kickass.systems/git/rrix/matrix-client.git

** exul slides :missing:
** federation tester :missing:
** gc :missing:
** go-neb

Multi-purpose Matrix bot. https://github.com/matrix-org/go-neb

** id :missing:
** identity server :missing:
** irc network list :missing:
** ivar

https://github.com/torhve/ivar2

** matrigram

If anyone is interested in using a telegram bridge, we'd love to hear some feedback https://github.com/GalPressman/matrigram

** matrix on freenode :missing:
** matrix-recorder

Okay, I think a first version is finally done: https://gitlab.com/argit/matrix-recorder - the idea is that the tool would allow you to keep a record of your conversations, as Riot does not yet allow you to export your message history in a format suitable for safekeeping.

** migrating to postgres :missing:
** mubot

https://github.com/davidar/hubot-matrix

** mxid :missing:
** network list :missing:
** olm :missing:
** receipt :missing:
** reindex

TIL that PostgreSQL may have internal fragmentation in the btrees used for indexes, and that can cause VACUUM FULL to make the database bigger... which can be solved by issuing a REINDEX DATABASE - https://matrix.to/#/!cURbafjkfsMDVwdRDQ:matrix.org/%2414835668811638615xXMYC:matrix.org

** screen sharing :missing:
** setting up federation

https://github.com/matrix-org/synapse#setting-up-federation has words on it.

** slack bridge
*** Matrix-org

https://github.com/matrix-org/matrix-appservice-slack

*** kfatehi

https://github.com/kfatehi/matrix-appservice-slack

** slack hook

See https://matrix.to/#/!svJUttHBtRMdXmEhEy:matrix.org/$14836112541869035fxcVU:matrix.org

** synpurge :fixme:

Utility script to Matrix room history purge room in Synapse https://github.com/aperezdc/synpurge. Synpurge has reached v4! https://pypi.python.org/pypi/synpurge/4

** telegram bridge
*** telematrix (Sijmen Schoon)

https://github.com/SijmenSchoon/telematrix

** those little circles :missing:
** upgrade script :missing:
** webrtc tutorial
*** Basics

https://www.html5rocks.com/en/tutorials/webrtc/basics/

*** Infrastructure

https://www.html5rocks.com/en/tutorials/webrtc/infrastructure/

** xmpp bridge
*** matrix-xmpp-bridge

https://github.com/pztrn/matrix-xmpp-bridge

*** xmpptrix

https://github.com/SkaveRat/xmpptrix

** yzord :missing:
* Processing Queue

Things which probably need to be added, but need a closer look.

** https://github.com/turt2live/matrix-appservice-instagram
** The IRC wish list is at https://github.com/matrix-org/matrix-appservice-irc/issues/208, and geekshed is already on the list.
